#--------------------------------------#
# R shiny Reference Box
#--------------------------------------#

referenceContent <- reactive({
  switch(input$ref,
         "Ransick et al. (mouse, recommended)" = {
           content <- "<em>Ransick et al., 2019:</em><br>
              <p>Murine kidney cell atlas generated with Illumina Hi-Seq sequencing by 10X Genomics Chromium platform.
              Kidneys were derived from 2 adult male and 2 adult female C57BL6/J mice. 
              High resolution atlas as prior to cell dissociation kidney was subdivided into cortex, the outer medulla and the inner medulla. 
              30 cell clusters were identified containing epithelial, endothelial, stromal and immune cell types.</p><br>
              <p>Data was downloaded from <a>https://github.com/qinzhu/kidneycellexplorer/tree/master/data</a> (2023/02/03). 
              Detailed description of the cell types displayed in the legend was downloaded from: <a>https://cello.shinyapps.io/kidneycellexplorer/</a> (2023/02/20)</p>
              <br><p>Reference: <em> Ransick, A., Lindström, N.O., Liu, J., Zhu, Q., Guo, J.-J., Alvarado, G.F., Kim, A.D., Black, H.G., Kim, J., McMahon, A.P., 2019. 
              Single-Cell Profiling Reveals Sex, Lineage, and Regional Diversity in the Mouse Kidney. Dev. Cell 51, 399-413.e7. <a>https://doi.org/10.1016/j.devcel.2019.10.005</a>
              </em></p>"  
         },
         "Novella et al. (integration of multiple mouse references)" = {
           content <- "<em>Novella et al., 2023:</em><br>
              <p>Kidney cell atlas of healthy adult mouse kidney generated by integrating single cell and single nuclei RNA sequencing data from 59 publicly
              available datasets of 8 independent studies using the machine learning algorithm single-cell hierarchical progressive learning (scHPL).
              scHPL automatically infers cell hierarchies from annotated datasets and builds a classification tree that can be used to classify unlabelled cells.</p>
              <br><p>Reference: <em>Novella-Rausell, C., Grudniewska, M., Peters, D.J.M., Mahfouz, A., 2023. A comprehensive mouse kidney atlas 
              enables rare cell population characterization and robust marker discovery. iScience 26. <a>https://doi.org/10.1016/j.isci.2023.106877</a></em></p>"
         },
         "Park et al. (mouse)" = {
           content <- "<em>Park et al., 2018:</em><br>
              <p>First single cell RNA sequencing atlas of the mouse kidney generated with droplet-based single cell RNA sequencing. 
              Kidneys were derived from 7 healthy male mice. 
              24 cell clusters were identified containing epithelial, endothelial, stromal and immune cell types.</p><br>
              <p>Data was downloaded from Gene Expression omnibus (GEO; accession no. GSE107585) and further processed with Seurat v2.3.4 for normalization. Cell types <q>novel 1</q> and <q>novel 2</q> were removed.</p><br>
              <p>Reference: <em> Park, J., Shrestha, R., Qiu, C., Kondo, A., Huang, S., Werth, M., Li, M., Barasch, J., Suszták, K., 2018. 
              Single-cell transcriptomics of the mouse kidney reveals potential cellular targets of kidney disease. Science 360, 758–763. <a>https://doi.org/10.1126/science.aar2131</a></em></p>"
         },
         "Lake et al. (human)" = {
           content <- "<em>Lake et al., 2023:</em><br>
              <p>Droplet-based single nucleus RNA sequencing dataset from human kidney generated with Chromium v3 platform. 58 kidney biopsies were derived from 35 healthy human donors.
              77 cell cluster were identified, including epithelial, endothelial, stromal, immune and neural cell types. </p><br>
              <p>The h5Seurat file of snRNA-seq data was downloaded from Kidney Cell Atlas website kpmp.org repository section on 2023/11/30. Cell type names and abbreviations were adapted from supplementary table 4 of <em>Lake et al.</em>.</p><br>
              <p>References: <br><em>https://www.kpmp.org accessed on 2023/11/30</em><br>
              <p><em>Lake et al., 2023. An atlas of healthy and injured cell states and niches 
              in the human kidney. Nature 619, 585–594.</em></p>"
         }
  )
  content
})